### ISSUE TITLE
As a user, I have options of a couple of cities for which I can see the air pollution, water quality, and CO2 emissions when searching the link directly, so that I can be informed about more than one city

### ISSUE THREAD

**Issue by smandic9** [ucsb-cs48-s20/project-s0-t2-env#23]
- [x] update the MongoDB database so that there are multiple cities 
- [x] update corresponding fields to ensure that every city has the same information provided
Note: there is no associated pull request because the changes were done in the mongo db databse.

**Comment by sssaaaaaarrra** [comment]
We updated the MongoDB data-base to include 10 of the largest cities in California and filled out the population, longitude and latitude, Carbon emissions, city name, and county name.
