### ISSUE TITLE
lab 10 part 3 cleanup

### ISSUE THREAD

**Issue by sssaaaaaarrra** [ucsb-cs48-s20/project-s0-t2-env#74]
- [x] find all PRs and commits possible since graphs are not accurate
- [x] format the data nicely

**Comment by katelynzzz** [comment]
Katelyn's Commits (Chronological Order):
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/3ec63ef69603067050a886b2eb8c0efddf7a9563
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/b2c3d8ba1ec093c9ed1d890d15db398a4e294453
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/f120362dc16387d8bde9e6efafda7a138b0854e0
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/071068c4d1389cb53fee4657c60ec861a706cf33
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/82e1864275259d9804ba29ccbcea3c01469c283c
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/7abe8fb09c20fd5dadc7476ca7e2ab8aac3f4870
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/6e6128613682fa8c385c3d9caca4b3d9ce70a9ac
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/a63b69ad77195a479ace50968712984578c758e5
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/6fd0e5e67e6d79befcad3a8519ae93c471c6afc1
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/efca2269f6c8e1ed21e26e1f909f24676e95801f
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/949eeb7206be175d4b52753987144bcf99a468ce
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/62c823207b3aa8157f9b5573c040faba9f0515b6
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/5f75c30448eb2e362d4520578b7390216e4c7a5a
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/c51abeae53c7b9d6ec2a79911c7ff69621064ce7
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/e64bb882cb73478ad52d2c17fda818c02749e552
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/7fbb117858df961879965df1d810587cba84caed
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/875ce1cbacdd3e3b7e2ef5a844d44c9493aeb249
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/faf3a5ab2867fa02605ddca93fdb1f70e2d120dd
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/8e73743bccc660261c4279db46fb6335a5d43dd1
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/a4f7e32db172e4b8dc1f29109043bb2506adc790
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/8f5ef64efe1cc7d182e14fc7ffa9f44b4bcb226a
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/6400af89749a237321b9a063aee23b60f736d6ac
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/8463d8ee711104278735f4364fd4be63e8b10c11
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/1a4cd3b52067f7f8f6fd063ec829fd3f6dda79d5
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/19d61fed77c0bf5d1be77fa59077e118ed019236
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/41ee0feed48527f4027db25f51d244f067dd6a9b
https://github.com/ucsb-cs48-s20/s0-t2-env-REPORT/commit/d0b45d78359c197b58d4d7d28ab045362306375a

(commits: , additions: , deletions: )
